### ISSUE TITLE
Duplicate words in terms list

### ISSUE THREAD

**Issue by Mycheze** [jzohrab/lute-v3#105]
**Description**

I just noticed that I have a whole bunch of the same word in my first page. I don't know if there are more words like this.

**To Reproduce**

Steps to reproduce the behavior, e.g.:

I have no idea how this happened, I just noticed it when looking into my terms list.

**Screenshots**

If it will be helpful, add screenshots.
![image](https://github.com/jzohrab/lute-v3/assets/71797685/5a0cbb74-70fb-48ce-9c94-762c7076de08)

**Extra software info, if not already included in the Description:**

- OS (e.g., iOS, windows): Pop_OS
- Browser (e.g., chrome, safari): Chromium
- How you've installed Lute (Docker, python, source): Python via pip
- Version: 3.0.6

**Comment by jzohrab** [comment]
I just noticed this and fixed it in the `develop` branch.  I'm _pretty_ sure the fix will also fix your issue.

**Comment by Mycheze** [comment]
I just found another (if you need, but it sounds like it's hopfully fixed :stuck_out_tongue: )
![image](https://github.com/jzohrab/lute-v3/assets/71797685/a6672848-5f21-4c7a-81d2-e37bddc3968b)

**Comment by jzohrab** [comment]
Launch in 3.0.9.
