### ISSUE TITLE
Can't access Lute if backup didn't complete 

### ISSUE THREAD

**Issue by dgc08** [jzohrab/lute-v3#112]
If have set my backup path to an USB. The problem is, if i haven't plugged my USB in, the backup won't complete. I can't access the Lute starpage then, because if I click "back to home" Lute just retries the update.

I suggest we remove the "Back to home" link if the backup failed and replace it with an "Retry" (just reload the page) and "Skip this backup" option.

**Comment by jzohrab** [comment]
That’s a great idea. I hadn’t considered the backup path being gone and this is a good solution.

**Comment by jzohrab** [comment]
Merged into `develop`, will be in next launch.

If backup fails, now shows links "retry", "fix settings", and "skip this backup".

**Comment by jzohrab** [comment]
Launched in 3.1.1
