### ISSUE TITLE
Add --update option to lute/main.py that calls sys.executable -m pip install -y lute3

### ISSUE THREAD

**Issue by mzraly** [jzohrab/lute-v3#120]
When a new lute update is available, it should be possible to update with a single command.

I normally run lute using virtualenv with a wrapper script that activates the right environment.  No doubt there are other users doing something similar, adding a script that sets up the environment and passes command-line arguments to the python -m lute.main command.

At the moment, upgrading the python environment requires establishing the environment (activating a virtual env, running via docker, setting environment variables, or whatever) and THEN calling pip to upgrade.

Adding a --upgrade option to lute.main would let all these users update using the same wrapper.

Implementation should be simple:

1. Import sys and subprocess
2. Add a new boolean --upgrade option
3. Upgrade using: subprocess.run([sys.executable, "-m", "pip", "install", "--upgrade", "lute3"], check=True)

**Comment by jzohrab** [comment]
I think I'd like to keep main.py strictly for starting Lute ... but hey, that's just me, and I can ignore the option I suppose!

In addition to the code change, please suggest the relevant documentation changes to the Lute manual.  https://github.com/jzohrab/lute-manual

Docker uses shouldn't update their lute, they should either use the pre-built image, or build their image from source.

**Comment by mzraly** [comment]
Hmm, I hadn't thought about the docker image, and updates not being persistent.  I updated the --help output accordingly.

Would you like a pull request to update install/install.md?  Or should I just write suggested changes here?

**Comment by jzohrab** [comment]
Do we even need this at all?  The page
https://jzohrab.github.io/lute-manual/usage/updating.html covers what's
needed, and any wrapper scripts are going to need to add the flag etc.

**Comment by mzraly** [comment]
Fair enough, let's kill this issue and PR.

**Comment by jzohrab** [comment]
Closing, thanks -- but perhaps there is something that should be done for boilerplate startup scripts for each environment.  I have my mac script, isán posted something about a windows/powershell, and I think another user had a linux script.  I'll open a separate issue for that, some people may find it useful.
