### ISSUE TITLE
I suggest adding mecab to prereqs on the Development page. 

### ISSUE THREAD

**Issue by Ambiaence** [jzohrab/lute-v3#128]
**Description**

I think that mecab should be added as a prerequisite on the [https://github.com/jzohrab/lute-v3/wiki/Development](https://github.com/jzohrab/lute-v3/wiki/Development ) page. While it is mentioned on the user install page, there is no implication that you need it as a developer. This would have saved me a bit of time had it been an explicit prerequisite.

**Example**

# Prereqs
* To work on Lute v3, you'll need at least Python 3.8 and pip. You'll probably want to use some kind of virtual environments; I use venv and so will write that out here.

* Note that GitHub CI tests Python versions 3.8 through 3.11, as we can't be sure what version of Python users have, so stay away from newer language features.

* Install Mecab according to your platform as described on the [User Installation Page](https://jzohrab.github.io/lute-manual/install/install.html). This is required for passing unit tests irrespective of whether you are developing features relevant to the Japanese language.

**Comment by jzohrab** [comment]
Thanks for the notes!  I wrote this but yours is the first “stress test” of
the docs so you worked through my implicit assumptions.  Thanks for your
patience. Have a good one, will incorporate soon.
