### ISSUE TITLE
Link seems broken on development page.

### ISSUE THREAD

**Issue by Ambiaence** [jzohrab/lute-v3#132]
Under the [Development Heading](https://github.com/jzohrab/lute-v3/wiki/Development#Development) located on the [Development Page ](https://github.com/jzohrab/lute-v3/wiki/Development) of the Wiki there is a link that looks and behaves like this, [Lute's architecture](https://github.com/jzohrab/lute-v3/wiki/architecture.md). 

This does not resolve to the [Architecture](https://github.com/jzohrab/lute-v3/wiki/Architecture) page as I assume it is supposed to. 
It links to `https://github.com/jzohrab/lute-v3/wiki/architecture.md` which can't be found and is then sends me to `https://github.com/jzohrab/lute-v3/wiki/` probably as a 404. When I go to a fictional page like `https://github.com/jzohrab/lute-v3/wiki/fakepage.md` the same thing happens. I imagine this did in fact work on a local machine, but the name resolution rules change when it lands on github.

**Comment by jzohrab** [comment]
Thank you, fixed.  This used to be in a different location where the links worked, and broke during transfer to the wiki.  Appreciate the ping!
