### ISSUE TITLE
Set current language to filter book list and set default language when creating books

### ISSUE THREAD

**Issue by mzraly** [jzohrab/lute-v3#133]
While working on one language and adding multiple books in one session it is frustrating to have to specify the language each time when adding a new book.  It would be nice to optimize the process of adding new books by being able to specify a current language that serves as the default language for book addition and a default search query in the books list, in addition to whatever else might be in the search box.

This would be especially helpful for someone working on multiple languages with lots of material in each.

Note that simply archiving books that are not in the target language is not efficient for users who are working on multiple languages and have many books in each of those languages.

There are a number of possible UI designs for this.  Some ideas, not mutually exclusive:
* Add a "default language" combo box to the settings page
* Add a "default language" combo box to the home page
* Add a "make language default" link to each language entry on the languages page

It would be nice to retain the default language setting across invocations so perhaps the settings page is the most appropriate place to set this.  But there should probably be some indication of what the default language is set to on the home page.

**Comment by jzohrab** [comment]
Belated thanks to @mzraly for the issue.  :wave:

Adding a combo box to the home screen is the clearest and a good enough start for this idea.

![image](https://github.com/jzohrab/lute-v3/assets/147004033/470ec878-de77-4b25-9159-6beff56a0c11)

**Comment by jzohrab** [comment]
Current direction I'm going with this, should suffice as a first pass.  Still not working yet, but selecting the lang will filter the book list and will auto-set the lang dropdown for books and terms:

> ![Image](https://github.com/jzohrab/lute-v3/assets/1637133/00762ae8-6865-4a26-a31d-ac101586f1a9)

**Comment by jzohrab** [comment]
Completed in develop.

**Comment by M-Biggles** [comment]
"First pass" but it's damn near perfect as it is!

The only things left to do would be to add it to the terms index page - in the same place, next to the search box. That's perfection! (I know it's already in the filters, but this seems to be the better solution).
