### ISSUE TITLE
Separate Word Count and % Known into separate columns and support sorting

### ISSUE THREAD

**Issue by mzraly** [jzohrab/lute-v3#138]
When presented with a large number of books (perhaps after importing a bunch from a friend or perhaps at some future date when lute ships with an initial set) it would be useful to be able to select the next book to study based on size (word count) or comprehensibility (% known).

The simplest implementation I can think of would be making the word count and % known values separate columns in the Books display, and making those two columns sortable.

**Comment by patrickayoup** [comment]
+1 I would also appreciate the ability to sort by % known

**Comment by jzohrab** [comment]
Added this as a byproduct of some other work, it will be in the next release.  cheers!

**Comment by jzohrab** [comment]
Launched in 3.1.1
