### ISSUE TITLE
Add faq/language config page for dictionaries that need "*" pre-pended

### ISSUE THREAD

**Issue by patrickayoup** [jzohrab/lute-v3#149]
**Is your feature request related to a problem? Please describe.**

My preferred dictionary is Glosbe, but when configuring Lute to use Glosbe, the dictionary does not load in the embedded frame despite Glosbe returning a 200. When observing the response headers, I noticed that X-Frame-Options is set to DENY. My understanding from [this page](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options) is that this header prevents a page from being embedded into a frame on another page. This essentially makes Lute and Glosbe incompatible.

**Describe the solution you'd like**

Lute could potentially check for this response header and provide an alternate display such as rendering a link instead to open Glosbe in a new tab. Being able to integrate the content directly into Lute would be nice, but this is a much more complicated solution than providing a link to open Glosbe.

**Describe alternatives you've considered**

See previous section.

**Additional context**

I have observed this behavior in both Chrome and Safari.

**Comment by jzohrab** [comment]
Hi there, the workaround for this is to add a “*” character at the start of the dictionary url in the form.  Lute opens such urls in a popup window.

I thought I had documented this, will have to check. Sorry if not!

**Comment by patrickayoup** [comment]
Thanks, that works well enough.

**Comment by jzohrab** [comment]
I need to add a faq entry for this, it's a common question. :-)  Cheers!

**Comment by jzohrab** [comment]
Added some docs and faq.
