### ISSUE TITLE
Error restarting Lute after upgrade to 3.1.0

### ISSUE THREAD

**Issue by stefanschweigert** [jzohrab/lute-v3#152]
**Description**

Unable to start Lute again when upgrading from 3.0.11 to 3.0.12

**To Reproduce**

Steps to reproduce the behavior, e.g.:

1. Stop currently running process on Windows 11.
2. Execute pip install --upgrade lute3
3. Run python -m lute.main

The process fails to start as usually with the below error.

**Screenshots**

Error during startup:
[Errno 2] No such file or directory: 'C:\\Users\\sschweigert\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\lute\\db\\setup\\..\\schema\\migrations_repeatable\\trig_wordparents_after_insert_update_parent_WoStatus_if_following.sql'
Please try again, or report an issue on GitHub.

**Extra software info, if not already included in the Description:**

- Window 12
- python install
- Version: 3.0.12

**Comment by jzohrab** [comment]
Thanks for the issue.  Though I can't check windows, I have a feeling it's due to file path length ... that string that you're showing is 260 chars.  Windows path run.  I'll make the file paths shorter in a beta release, we can chat on Discord about updating (I'll ping you there).

**Comment by jzohrab** [comment]
I've pushed beta release `3.1.1b1` which shortens the file names.  The old file paths were 260 chars, which may be too long (by default, Windows uses a path length limitation (MAX_PATH) of 256 characters).  The new migration paths are 211 chars, much shorter.

To do a pip upgrade, you need to explicitly specify the beta version:

```
pip install lute3==3.1.1b1
```

Give it a shot @stefanschweigert -- thanks again for the ping!

**Comment by stefanschweigert** [comment]
Thanks @jzohrab! It is now able to run. I tend to hit path length errors sooner that others with my last name :).

Really enjoying Lute, thanks so much for your work on this excellent tool!

**Comment by jzohrab** [comment]
Great that the fix worked.  It will be in the next release.  Cheers!
