### ISSUE TITLE
[Classical Chinese] preload default Dictionary 1 - clicking a word redirects to dictionary 1 entry page

### ISSUE THREAD

**Issue by farahpharos** [jzohrab/lute-v3#16]
**Description**
When using https://ctext.org/dictionary.pl?if=en&char=### as a dictionary 1, clicking a word in the text 

**To Reproduce**

Steps to reproduce the behavior, e.g.:

1. Create new language and use Classical Chinese preload settings
2. Import a chinese language text and click on any highlighted word
3. Page will be redirected to the ctext.org definition page

This issue does not come up with other dictionaries such as:
https://www.archchinese.com/chinese_english_dictionary.html?find=###

**Extra software info, if not already included in the Description:**

- OS: Both Mac and Windows
- setup: docker 
- Version: 2.1.3 (@latest version)

**Comment by jzohrab** [comment]
I don't think there's anything that we can do here -- at least, the dictionary can be opened in a new tab.  PR #298 changes the dictionary, that's a reasonable change for now!
