### ISSUE TITLE
Can't edit pasted text in the Parents field

### ISSUE THREAD

**Issue by mzraly** [jzohrab/lute-v3#164]
**Description**

When I am reading a document I often encounter a conjugation of a verb that I want to add to the Terms list with the infinitive form of the verb as its parent.

I was previously able to paste the conjugated form of the verb in the Parents field, press the backspace key a few times to remove the conjugation ending, and then select the infinitive form from the list of matched terms that appears below the text entry field.

Now, if I paste the conjugated form in the Parents field it immediately transforms into a tag object, and hitting backspace deletes the entire tag rather than deleting the characters at the end of the conjugated form.

This affects any language but is most bothersome when I need to use a different character set to enter the text I want in the Parents field.  Before I didn't have to switch keyboard settings to copy and delete characters from a word written in Hindi Dev Nagari script.  Now I have to switch keyboards to enter the text without pasting, then switch back to enter the translation.

**To Reproduce**

1. Read a book
2. Select a word
3. Copy the word into the clipboard
4. Paste the word into the Parents field
5. BOOM it's a tag that can't be edited, only deleted.

**Screenshots**

None

**Extra software info, if not already included in the Description:**

- OS (e.g., iOS, windows): Linux
- Browser (e.g., chrome, safari): Firefox
- How you've installed Lute (Docker, python, source): python pip
- Version: 3.1.1 (but bug was introduced earlier)

**Comment by jzohrab** [comment]
Thank you @mzraly .  I switched the tagging library recently (necessary for various reasons) and that had this effect.  I'll check to see if there is a way to allow pasting without the 💥 BOOM 💥 ... hopefully there is.

**Comment by jzohrab** [comment]
Fixed in `develop`, thanks.

Immediately after paste:

> <img width="150" alt="image" src="https://github.com/jzohrab/lute-v3/assets/1637133/cd1e20ef-5ca8-4460-9a9d-8fd055e826da">

Hit backspace immed. after paste:

> <img width="166" alt="image" src="https://github.com/jzohrab/lute-v3/assets/1637133/1f173e95-018d-402c-8d11-e5e4ef09751b">

and tag is editable.
