### ISSUE TITLE
New Lines in Translation field are not respected on the Terms page

### ISSUE THREAD

**Issue by M-Biggles** [jzohrab/lute-v3#166]
**Description**

When I create a new line in the translation field (excuse my weird way of doing hints!):

![1A](https://github.com/jzohrab/lute-v3/assets/156795688/0f3468df-f9a2-4091-ae93-f016bf79f91f)
![1B](https://github.com/jzohrab/lute-v3/assets/156795688/1110e8ec-3ae6-4fff-a714-b0ad5551c603)

I see this on the terms page:

![2](https://github.com/jzohrab/lute-v3/assets/156795688/b22aad72-fa26-45d7-92e2-59aa46e280b9)

It would be useful if it kept the new lines.

**Comment by jzohrab** [comment]
Thanks, fixed in `develop` branch, will be in the next launch. 👍 

> <img width="75%" alt="image" src="https://github.com/jzohrab/lute-v3/assets/1637133/52650ba8-b92b-4dd9-aec4-3ebed690bfaf">
