### ISSUE TITLE
Optimize backups

### ISSUE THREAD

**Issue by jzohrab** [jzohrab/lute-v3#173]
Currently, the backup takes a fair amount of time.  We can probably cut this down dramatically.

The backup has two parts:

* backup the db
* backup images

Note that audio is currently _not_ backed up, as those files might be large ... I should really back them up though!

I am 99% sure that the db backup is very fast, and the image backup is where the time is spent.  The image backup is currently very dumb: it just copies all of the files to the backup location, even if those files already exist in the backup location.  This should be changed to only backup missing or changed files.

**Turns out I was totally wrong about the image stuff being the problem, it was the db compression.**

## Design

* First check that the db backup time is fast (logging)
* Speed up image backup: always copy new files; only copy existing files if the file has changed (first iteration will just check the file content to see if it's changed).  The change can probably be done simply with built-in methods e.g. https://docs.python.org/3/library/filecmp.html#filecmp.cmp.
* with sped up image backup, audio could also be backed up efficiently

## Tests

* set up image dirs; test cases: same filename, same content; same filename, different content; new file; removed file (not removed from backup)

**Comment by M-Biggles** [comment]
Perhaps you could move the backup menu to the Settings menu and have a Backups page with the Date of Last Backup, Backup directory and add the ability to load a backup at any point (replacing the current data - with sufficient warning and verification).

**Comment by jzohrab** [comment]
The automatic backup is the problem, with the length of time it takes to do it. It does get to be annoying sometimes :-)

> the ability to load a backup at any point

That's a nice idea, should be created separately.

**Comment by jamesdeluk** [comment]
Personally I've never had an issue with the backup duration, but having to manually move audio is a main (especially as I'm copying from Windows to Android). Having an option (i.e. perhaps not done by default) to include the audio in the backup archive would be great!

**Comment by jzohrab** [comment]
> include the audio in the backup

I'll do audio by default until it's needed to not do it by default, every option means another code path etc.  Audio should be straightforward once the image stuff is sorted out.  (I hope)

**Comment by jamesdeluk** [comment]
> > include the audio in the backup
> 
> I'll do audio by default until it's needed to not do it by default, every option means another code path etc. Audio should be straightforward once the image stuff is sorted out. (I hope)

That's fine by me - the optionality was just in response to your large filesize comment. For now I'm just using a simple .cmd script to copy the useraudio folder.

Of course being able to restore from the application itself would also be incredibly useful!

**Comment by jzohrab** [comment]
> optionality was just in response to your large filesize comment

Thanks @jamesdeluk - thinking about it again, I'll make it optional. :-)  That will be in a separate issue as it implies a few more things.  Added https://github.com/jzohrab/lute-v3/issues/210.

Restore from app is in #188 .

**Comment by jzohrab** [comment]
ChatGPT first draft of code, needs work around file equality check but good enough:

```
import os
import shutil

def backup_folder(source_folder, backup_folder):
    for root, dirs, files in os.walk(source_folder):
        relative_root = os.path.relpath(root, source_folder)
        backup_root = os.path.join(backup_folder, relative_root)
        os.makedirs(backup_root, exist_ok=True)
        for file in files:
            source_file = os.path.join(root, file)
            backup_file = os.path.join(backup_root, file)
            # st_mtime not a good metric, change
            if not os.path.exists(backup_file) or os.stat(source_file).st_mtime > os.stat(backup_file).st_mtime:
                shutil.copy2(source_file, backup_file)
```

test from spec

```
import os
import shutil
import pytest

from backup_script import backup_folder

@pytest.fixture
def create_test_files():
    # Create test files in folder A
    os.makedirs("A/1", exist_ok=True)
    os.makedirs("A/2", exist_ok=True)
    os.makedirs("A/3", exist_ok=True)
    with open("A/1/a.jpg", "w") as file:
        file.write("abc")
    with open("A/1/b.jpg", "w") as file:
        pass
    with open("A/2/c.jpg", "w") as file:
        pass
    with open("A/2/d.jpg", "w") as file:
        file.write("xyz")
    with open("A/3/f.jpg", "w") as file:
        pass

    # Create existing files in folder B
    os.makedirs("B/1", exist_ok=True)
    os.makedirs("B/2", exist_ok=True)
    with open("B/1/a.jpg", "w") as file:
        file.write("def")
    with open("B/2/d.jpg", "w") as file:
        file.write("xyz")
    with open("B/2/e.jpg", "w") as file:
        pass

def test_backup_folder(create_test_files):
    backup_folder("A", "B")
    assert os.path.exists("B/1/a.jpg")
    assert os.path.exists("B/1/b.jpg")
    assert os.path.exists("B/2/c.jpg")
    assert os.path.exists("B/2/d.jpg")
    assert os.path.exists("B/2/e.jpg")
    assert os.path.exists("B/3/f.jpg")
    with open("B/1/a.jpg") as file:
        assert file.read() == "abc"
    with open("B/2/d.jpg") as file:
        assert file.read() == "xyz"
```

**Comment by jzohrab** [comment]
Well, this is interesting ... turns out it is the db zip that takes time.  Here's the hour-min-seconds of the steps in lute/backup/service.py:

```
13-43-34 - start image backup
13-43-36 - done image backup
13-43-36 - create db backup
13-43-47 - done db backup, remove extra
13-43-47 - done remove extra
```

11 seconds for a db backup, to create a 12 MB file seems excessive.

**Comment by jzohrab** [comment]
Reducing the gzip compression level from 9 to 4 cuts time down to one second, and the file size only increased from 12MB to 13MB for my db (from initial size of 40MB).

**Ridiculous.**

**Comment by jzohrab** [comment]
Backups much faster, and they redirect to home if they're successful, so less user interruption.

Fixed in develop.

**Comment by jzohrab** [comment]
Launched in 3.2.7.
