### ISSUE TITLE
Preserve blank lines between paragraphs in input text

### ISSUE THREAD

**Issue by jzohrab** [jzohrab/lute-v3#175]
Sometimes when creating books there are blank lines:

```
here is some content

other stuff.
and more.
```

Lute should leave the blank lines, so it would be rendered like:

```
<p>here ...</p>
<p></p>
<p>other stuff.</p> ... etc
```

I believe that it currently strips extra blank lines.  There's really no need to do that.

**Comment by M-Biggles** [comment]
This was on my list. Glad to see it added!

**Comment by jzohrab** [comment]
Saving the blank lines:

```
Welcome to Lute! This short guide should get you going.

Navigation
This tutorial has multiple pages. At the top of the page is a slider to navigate forwards and backwards, or you can click the arrows at either end of the slider.

1. The Basics
All of these words are blue because they are "unknown" - according to Lute, this is the first time you're seeing these words.
```

Gives

> ![Image](https://github.com/jzohrab/lute-v3/assets/1637133/227c5a6f-a426-4ae5-91a7-570a4b2bf22b)

**Comment by jzohrab** [comment]
fixed in `develop`
