### ISSUE TITLE
stats show counts in bar graphs

### ISSUE THREAD

**Issue by jzohrab** [jzohrab/lute-v3#177]
e.g.

![Image](https://github.com/jzohrab/lute-v3/assets/1637133/1bd90dd2-0e4d-4bc3-9756-b77f11c7f802)

**Comment by jzohrab** [comment]
Added in `develop`

<img width="350" alt="image" src="https://github.com/jzohrab/lute-v3/assets/1637133/278a5169-e33d-45ac-92a9-0e325cc8ba19">

Note the stats is only a sample of the next few pages, it's not the full book.

**Comment by M-Biggles** [comment]
I remember some other reading software did this for the full counts and when you pressed the button, it would warn you that it was a heavy task and might take some time. Perhaps an option to allow 'Full Processing of Stats' would satisfy both perspectives on this one.

Using a sample of the texts can be better for books, but a lot of learner content could be heavily skewed towards having less unique words early on.
