### ISSUE TITLE
Export terms

### ISSUE THREAD

**Issue by Morio1987** [jzohrab/lute-v3#18]
Is it possible to add ability to export terms as a CSV or TXT file format? It would be awesome if we could export filtered terms, not all of them.

**Comment by jzohrab** [comment]
Hi @Morio1987 , I've moved this to the new v3 repo, I've stopped work on v2.  v3 will be out very soon, it's actually already in beta.

I'll see if I can get this going quickly.

**Comment by Morio1987** [comment]
> Hi @Morio1987 , I've moved this to the new v3 repo, I've stopped work on v2. v3 will be out very soon, it's actually already in beta.
> 
> I'll see if I can get this going quickly.

😍Perfect, Thank you very much

**Comment by jzohrab** [comment]
Added a simple export button to v3 beta:

<img width="719" alt="image" src="https://github.com/jzohrab/lute-v3/assets/1637133/bcf3813b-bf2b-4bb3-aa1b-429c9c64b7dc">

Documented in the manual - https://jzohrab.github.io/lute-manual/usage/terms.html

It's a simple solution for now, there's an open issue about exports with images, sentences, etc, but perhaps this will be enough for now.

**Comment by jzohrab** [comment]
I'll assume this is good enough for now.  Thanks again for the nudge :-)
