### ISSUE TITLE
Add filter to home page

### ISSUE THREAD

**Issue by M-Biggles** [jzohrab/lute-v3#181]
Would be nice to have a filter for Language, etc.

**Comment by M-Biggles** [comment]
It could be as simple as a single drop-down with the languages listed [All Languages, Language 1, Language 2, etc], and the rest could be sorted by column.

**Comment by jzohrab** [comment]
The book table has a little "search" box on the top right that searches each field.  eg "Fr" would return books with language "French".  It's not exactly what you're requesting but as a workaround it might be ok for now.

**Comment by M-Biggles** [comment]
Yeah, that does work.

This one just saves my lazy self from some work... :D

**Comment by jamesdeluk** [comment]
Also a filter/sort by completed would be useful.

**Comment by M-Biggles** [comment]
This is close enough to #133 and #204, so I'd say it can be closed.

**Comment by jzohrab** [comment]
Ah super thanks for helping managing the backlog.  👍
