### ISSUE TITLE
On larger resolutions, text listing stays narrow

### ISSUE THREAD

**Issue by M-Biggles** [jzohrab/lute-v3#183]
So, I've got a big screen and resolution (2560 x 1080) and the listing of texts is still quite narrow when the window is in full screen.

**Comment by M-Biggles** [comment]
Yeah, this one just seemed to be a browser issue. I'll keep an eye on it to see if there's anything consistent.

**Comment by jzohrab** [comment]
Yep I can't sort out how to make the table resize automatically.  Cheers!

**Comment by M-Biggles** [comment]
Yeah, I figured that! haha
