### ISSUE TITLE
Make 'Translation' box a bit bigger

### ISSUE THREAD

**Issue by M-Biggles** [jzohrab/lute-v3#190]
Using this translations box often - it's a small target and I miss it sometimes. Would be nice to make it a line or two bigger by default.

**Comment by jzohrab** [comment]
You can customize the field height though using a custom style.  From the home screen, settings > settings, add the following to the "custom styles" field:

```
textarea#translation { height: 150px; }
```

Then click save.  When you open the reading form, it will look like this:

> <img width="75%" alt="image" src="https://github.com/jzohrab/lute-v3/assets/1637133/81f4e9dc-3734-4018-be4d-3476ff3686f3">

as opposed to the default:

> <img width="75%" alt="image" src="https://github.com/jzohrab/lute-v3/assets/1637133/3fb47b3a-222a-4a33-8186-89de1d0f6ec1">

**Comment by M-Biggles** [comment]
Champion, thanks!

Is there a full list of the things I can style?

**Comment by M-Biggles** [comment]
I see that this page with all the styles exists: https://github.com/jzohrab/lute-v3/blob/master/lute/static/css/styles.css

Still, I'm not a coder and it's mostly a mystery to me. So, perhaps it should be a goal to create a visual guide for the clueless? I'd be happy to do them one-by-one once I figure out what they are and take screenshots and show changes.

**Comment by jzohrab** [comment]
Right, I understand, CSS can be pretty cryptic! :-)

Many things can be styled.  The best way to sort it out is to get some kind of "elements" view of the page -- e.g. in chrome dev tools, you can right click an element, click Inspect, and see stuff about it.  (I'm getting buried with stuff and can't spend much time showing you this :-) ) -- but eg. with an id like "blah" in `<span id="blah">something</span>` you can style the span with that id like this:

`span#blah { font-size: 200%; }`

or, for all elements with a certain class (e.g. `<span class="x y z">hello</span>` -- this has 3 classes!) you can say

`span.x { ...styling ...}`

There are some more examples at https://jzohrab.github.io/lute-manual/usage/themes/custom-styles.html

**Comment by M-Biggles** [comment]
I'll do some experimenting and at a later date, we can look into creating a more in-depth guide. I'm happy to offer my own help when the time comes.

**Comment by M-Biggles** [comment]
> I'm getting buried with stuff and can't spend much time showing you this :-) 

Sorry for contributing to this!!!

I promise that I'm basically done. I've reported 90% of the stuff that I've found I've found so far and there are only a few things I'm still considering and a few that would be dependent on other features becoming reality first (I can plant seeds though... hehe).
