### ISSUE TITLE
Move Lute logo to more intuitive place on reading page

### ISSUE THREAD

**Issue by M-Biggles** [jzohrab/lute-v3#196]
This:

![A](https://github.com/jzohrab/lute-v3/assets/156795688/5f737c80-486b-4916-8e48-6239b7a64918)

would perhaps work better as this:

![B](https://github.com/jzohrab/lute-v3/assets/156795688/1cb8bf50-a5b3-45e0-b8eb-a6229c2b9527)

If (when?) you add collections, it would also be a good place for some arrows to move between items in the collection without having to go back up to the listing

**Comment by jzohrab** [comment]
Declining this one as at adds a lot of vertical space in the header bar, and is a design preference only.
