### ISSUE TITLE
Create system for converting audio files down to desired format

### ISSUE THREAD

**Issue by M-Biggles** [jzohrab/lute-v3#200]
This one is a bit bigger. Leave for Lute v4 or something...

It would be nice to have an option to set quality and format for storing audio files I upload to Lute. I know that tools like FFmpeg can convert just about anything. This way I can set my files to 192 or 128 and save on space.

**Comment by jzohrab** [comment]
This one should fall outside of Lute itself.  I don't control what tools people have on their machines, and wouldn't want to write a UI which would essentially map to control flags.  (But if someone else insists on implementing some kind of plug-in, it's not a bad idea :-) ).

**Comment by M-Biggles** [comment]
Yeah, this is a bit of a stretch goal.
