### ISSUE TITLE
Add drop down menu for each language

### ISSUE THREAD

**Issue by emanuelps2708** [jzohrab/lute-v3#204]
Hi jz, this is not very necessary but I think it would be good for organization mainly. The possibility to add a drop down menu (like a profile) for each language with the number of parents (or total terms, I don't know which one would be better) that one has, this could be helpful for people learning multiple languages, something similar to what LinQ has, it could also help if someone would want a custom setting for a specific language(I know there's a way to do it now with css, but it would be easier this way).

![image](https://github.com/jzohrab/lute-v3/assets/147004033/470ec878-de77-4b25-9159-6beff56a0c11)
(sorry the bad quality of the screenshot)

Thanks for all jz ;)

**Comment by M-Biggles** [comment]
After a bit of playing with Lute (and remember others that did the same), having to constantly select language while I'm adding texts, adding terms, etc, it's all a bit too much. I've caught myself editing a Yiddish term when it should be a Hebrew one until I noticed and stopped.

Seems like the cool new design feature but it's a pain in the rear of epic proportions. A site-wide filter would be super nice. Then you can also add 'Known words' next to it. Solves both issues.

**Comment by jzohrab** [comment]
Hi there, thx for the issue :wave:   I've not needed this b/c I'm (currently) only using it for Spanish, but makes sense.  Another person requested a "set current language" filter (#133), feels like the same idea.  I'd add "(all)" to the top of the list to just show everything.

If it's the same, I'll check the detail on the older issue and move stuff here if needed.
