### ISSUE TITLE
Focus and hover on different terms creates status update problems

### ISSUE THREAD

**Issue by jzohrab** [jzohrab/lute-v3#213]
From Discord:

> After the latest release, when creating a new term in the reader, once the word is saved, focus is still on the word that was added, so that if you hover over another word and change its status with the number keys, it changes the newly created word AND the one that you're hovering over.

adding new term "tìre"

![Image](https://github.com/jzohrab/lute-v3/assets/1637133/f1d8598c-ad2e-4fd2-90a9-f121f6dded1e)

"tire" created

![Image](https://github.com/jzohrab/lute-v3/assets/1637133/17fefef9-2f58-4bb6-bb9c-63097fb9db24)

hovering over "nan"

![Image](https://github.com/jzohrab/lute-v3/assets/1637133/1727735d-22aa-428d-9aa5-2c3502c2a980)

updated status of "nan", "tìre" updated as well

![Image](https://github.com/jzohrab/lute-v3/assets/1637133/f977ccf4-c802-4b51-995a-47bc2fe5e113)

**Comment by M-Biggles** [comment]
https://github.com/jzohrab/lute-v3/assets/156795688/2a4df6ac-52a3-43af-9b85-7333f5b413a5

**Comment by M-Biggles** [comment]
https://cdn.discordapp.com/attachments/1074759090338812016/1204990189139787826/bug.mp4?ex=65d6bd90&is=65c44890&hm=3a8b0131d4def32cb0cae882a523795c7711199a480b3c12095c982b05815688&

**Comment by jzohrab** [comment]
Fixed in `develop`.  There may yet be some other details I've missed because of different situations, but it seems fine:

* multiple words clicked, multiple terms updated with up/down
* word updated via form
* hover, and changing to clicked and back

**Comment by jzohrab** [comment]
Released in 3.1.4.
