### ISSUE TITLE
Pasting parent tag doesn't show dropdown

### ISSUE THREAD

**Issue by jzohrab** [jzohrab/lute-v3#216]
From Discord:

> What I'm looking for is a way to see if it has an entry already. Right now, if I paste, it just adds it as a parent, but there's no feedback about whether or not there's an entry for it

That feels sort of like a bug, there should be a way of indicating a new parent vs not.

**Comment by jamesdeluk** [comment]
Relatedly, if you paste the parent tag, it doesn't copy the status from the parent - you have to type and select the parent for the status to update.

Also, currently the parent drop down only appears after two letters (or, in Korean, two characters) have been typed. This would be better with one, at least for Korean.

**Comment by jzohrab** [comment]
Thanks for the extra info, appreciated.

(I've tried changing the parent to a single character -- it should be easy, but it's not working.  I'll open a new issue for more checking if I can't sort it out soon.  Thanks!)

**Comment by jzohrab** [comment]
> <img width="247" alt="image" src="https://github.com/jzohrab/lute-v3/assets/1637133/0087a2ba-e616-451e-a8d1-e069990c5455">

Fixed in `develop`, tried it a few different ways, feels correct.

**Comment by jzohrab** [comment]
Also, since you paste and then choose from the list, the parent linkage and status stuff should be ok now.

**Comment by jzohrab** [comment]
Released in 3.1.4.
