### ISSUE TITLE
Create new text/Edit text's texts fields don't resize horizontally.

### ISSUE THREAD

**Issue by M-Biggles** [jzohrab/lute-v3#223]
![1](https://github.com/jzohrab/lute-v3/assets/156795688/54b17cc7-f986-4a9d-b770-d3510d2b61e5)

These resize vertically but not horizontally.

**Comment by webofpies** [comment]
it can be set to resize in both axes by adding this rule to custom styles:
#translation {
  resize: both;
}

**Comment by M-Biggles** [comment]
> it can be set to resize in both axes by adding this rule to custom styles: #translation { resize: both; }

I just tried this which fixes it on all the pages:

textarea { resize: both; }

**Comment by jzohrab** [comment]
Right we should make this part of the default, I guess.  I can't see any reason not to have it in defaults.  @webofpies thoughts?  Anything weird this will do?

**Comment by webofpies** [comment]
@jzohrab it seems there's nothing weird. it'll go back to default size after each term form load.

**Comment by M-Biggles** [comment]
Having testing this out a bit, it works well enough with 'textarea { resize: both; }'. It can deform the rest if you expand it too much ,but it's useful in general.

You can only test it for yourself, @jzohrab. See how it feels.

**Comment by jzohrab** [comment]
Cheers will do!  If useful, great, quick addition. 👋

**Comment by jzohrab** [comment]
Changed in `develop`, thanks.

**Comment by jzohrab** [comment]
Launched in 3.2.1.
