### ISSUE TITLE
 Would it be possible to import Anki cards?

### ISSUE THREAD

**Issue by Ciana1220** [jzohrab/lute-v3#226]
Is there a way to import Anki cards? Would it be possible to import cards along with images and status?

**Comment by Ciana1220** [comment]
Hi, I want to import my Anki deck to Lute. I have this deck for studying japanese language focusing on vocabulary and I would like to know if there's any way to transfer these words to Lute

**Comment by jzohrab** [comment]
There's no direct import from Anki, but it's doable.  You could export your Anki stuff into a CSV, and edit it so it matches the required CSV format for Lute (see the manual: https://jzohrab.github.io/lute-manual/usage/terms/bulk-term-import.html).  I'm not sure how you'd set the statuses -- perhaps you could just set them all as "1" (new term) and then just update them in Lute as you go, the status updates are quick.

Images aren't imported, sorry!  That would need to be a new feature.  But at least having the words would get you started.

**Comment by jzohrab** [comment]
Closing, answered question, imports directly from Anki aren't in scope.
