### ISSUE TITLE
Support vocabulary lists

### ISSUE THREAD

**Issue by GrimPixel** [jzohrab/lute-v3#229]
**Is your feature request related to a problem? Please describe.**

There could be vocabulary lists, like the most common words https://github.com/frekwencja/most-common-words-multilingual

**Describe the solution you'd like**

Support vocabulary lists, so the user can try to learn according to the list.

**Comment by jzohrab** [comment]
What does "support vocabulary lists" look like?

**Comment by GrimPixel** [comment]
Yes. It baffles me. The word list can be considered as a book and learned as any other book.
