### ISSUE TITLE
Text imports mix up lines

### ISSUE THREAD

**Issue by Mycheze** [jzohrab/lute-v3#23]
**Description**

I've noticed that some lines (not very common, but some) are out of order from the original text file that was imported. I noticed this while listening along with an audiobook and certain things would be skipped then gone back to in a few moments. It's not an issue with the next file (see attachments).

**To Reproduce**

Steps to reproduce the behavior, e.g.:

1. Import using a text file
2. Notice that some lines are out of order

**Screenshots**

This is the text I confirmed with. [Harry Potter a Fenixuv rad - J. K. Rowling.txt](https://github.com/jzohrab/lute-v3/files/13450936/Harry.Potter.a.Fenixuv.rad.-.J.K.Rowling.txt). An example of a line that is out of place is `S mou drahou starou matičkou, ano` which is on line 1889.

Here it is in Lute out of order: 
![lutemixingupsomelines](https://github.com/jzohrab/lute-v3/assets/71797685/4d9e8d96-002b-4128-8e63-e63ce6f9a260)
![lutemixingupsomelines2](https://github.com/jzohrab/lute-v3/assets/71797685/35c08e1f-7c49-4b71-8d49-d9320517c58c)

**Extra software info, if not already included in the Description:**

- OS (e.g., iOS, windows): Pop!_OS
- Browser (e.g., chrome, safari): Chromium
- How you've installed Lute (Docker, python, source): Python (v3)
- Version: 3.0.0b11

**Comment by jzohrab** [comment]
Thanks, checked and fixed on v3.0.0.  This is a render-time problem, not import, the import works and doesn't mix up sentences.

Summary of the bug, fyi: at render time, the code parses the current text, and gets the paragraph numbers to write out.  The line `paranums = unique([t.paragraph_number for t in tokens])` uses python's `unique` function, but that wasn't preserving the order.  Oddly it has never occurred for me till now!  With `paranums = sorted(unique([t.paragraph_number for t in tokens]))` the numbers are sorted.

I'll make a release soon as this needs to be resolved.  Thanks!

**Comment by jzohrab** [comment]
Fixed in 3.0.1, launched, thanks!
