### ISSUE TITLE
Use TSV instead of CSV

### ISSUE THREAD

**Issue by GrimPixel** [jzohrab/lute-v3#232]
**Is your feature request related to a problem? Please describe.**

Quotation marks in CSV are from time to time required. This makes manual editing risky and adds efforts for format conversions.

**Describe the solution you'd like**

Use TSV instead.

**Comment by jzohrab** [comment]
I think multi-paragraph elements would cause the same delimiting/quotation problems for TSV as they do for CSV, so I'm not sure that this is going to buy us any real safety or ease of use.  Most spreadsheet programs (google, excel) handle CSV import/export correctly, I'd always advise people to use that.

Question back to you about the real need for this: it's extra stuff with limited ROI in my opinion, but that's just my opinion, interested in yours.  Thanks for the issue 👋

**Comment by jzohrab** [comment]
No response, won't change, both CSV and TSV have their own challenges.  CSV is fine.
