### ISSUE TITLE
Add a 'Focus mode'

### ISSUE THREAD

**Issue by shetozz** [jzohrab/lute-v3#238]
**Is your feature request related to a problem? Please describe.**

The right-side panel is kinda useless after you make the entries to the new terms.

**Describe the solution you'd like**

There should be a 'Focus mode' where the user can disable the right-side panel, have the text centered with some amount of padding on both sides, and the option to hide/show highlight.

**Describe alternatives you've considered**

Moving the side panel all the way to the right, but there's no option for padding now, so it makes text too wide and tedious to read.

**Comment by M-Biggles** [comment]
I had thought: it would be nice if we could "dock" the right-side panel by moving the divider all the way to the side. It won't open unless you drag it back open (or maybe a little tab?). Doesn't need to load anything but the tooltips when it's closed over. Possible?

**Comment by jzohrab** [comment]
In progress, pretty much done in #262 .  @M-Biggles your suggestion is good but we've gone with a "toggle" button for now.  ... Let's see how this new design idea works out.

**Comment by M-Biggles** [comment]
> In progress, pretty much done in #262 . @M-Biggles your suggestion is good but we've gone with a "toggle" button for now. ... Let's see how this new design idea works out.

Sounds great! Looking forward to it :)

**Comment by jzohrab** [comment]
Launched in 3.2.1.
