### ISSUE TITLE
Timed term pop-up window (frame)

### ISSUE THREAD

**Issue by GyckaZ** [jzohrab/lute-v3#239]
To have an option to leave the term pop-up window _(frame)_ open for X ms before it closes automatically after the mouse pointer is not on the term. The time (ms) could be defined in the setting, default - 0ms.

This could help with implementing other possible features in the future, like being able to navigate between the terms in a pop-up window.

**Comment by jzohrab** [comment]
Closing per discussing in Discord: hovering over the terms is good enough.
