### ISSUE TITLE
Add sorting of columns on Languages page (also add new ID column) -- switch to Datatables

### ISSUE THREAD

**Issue by M-Biggles** [jzohrab/lute-v3#240]
Title says it really.

The columns listing the languages can't be sorted by name, books or terms. There might be another column one day, who knows...

Adding an ID number column would help with sorting in the order we added them (with date possible?).

**Comment by jzohrab** [comment]
Right, makes sense.  The languages listing is just an HTML list, as opposed to the terms and books which use a library called datatables.  I wrote this page when first starting with this framework, so it was bare-bones.  It should be switched to datatables as well.  Thanks.

**Comment by jamesdeluk** [comment]
Also an option to hide columns completely.

**Comment by jzohrab** [comment]
Switched to datatables for sorting and filtering, was quick:

> ![Image](https://github.com/jzohrab/lute-v3/assets/1637133/09d6ac10-cd95-4430-b92e-4bf708c61ead)

Re "in the order we added them (with date possible?)." -- that's a separate issue, not sure if it's valuable for most users. :-)  I don't track "date_added" for most entities, even though I should have ... bad jz.

**Comment by jzohrab** [comment]
Released in 3.2.2
