### ISSUE TITLE
Parallel text

### ISSUE THREAD

**Issue by GrimPixel** [jzohrab/lute-v3#242]
**Is your feature request related to a problem? Please describe.**

I got multiple documents of the same content in different languages and would like to display them side-by-side.

**Describe the solution you'd like**

Add “versions” to a document; different “versions” have different properties like the language, the translator, etc.; two different versions can be displayed together.

**Additional context**

Example of parallel texts: https://www.grimmstories.com/

**Comment by jzohrab** [comment]
Dup of https://github.com/jzohrab/lute-v3/issues/172, closing.
