### ISSUE TITLE
Quick reading

### ISSUE THREAD

**Issue by GrimPixel** [jzohrab/lute-v3#245]
**Is your feature request related to a problem? Please describe.**

Training of faster reading speed can be available.

**Describe the solution you'd like**

Have a quick reader.

**Additional context**

An example: https://github.com/Darazaki/Spedread

**Comment by jzohrab** [comment]
This feels like it's well out of Lute's scope: Lute is for learning through reading, if you're talking about increasing reading speed then you've kind of already "graduated" from Lute. :-)
