### ISSUE TITLE
Cloze

### ISSUE THREAD

**Issue by GrimPixel** [jzohrab/lute-v3#246]
**Is your feature request related to a problem? Please describe.**

Text memorisation can be trained.

**Describe the solution you'd like**

Have clozes.

**Additional context**

An example: https://github.com/zg/text-memorize

**Comment by jzohrab** [comment]
Closing for reasons given in the manual: https://jzohrab.github.io/lute-manual/faq/why-no-flashcards.html

Adding testing is a massive effort which isn't really Lute's primary goal.  Instead I'd prefer to do #3 (opinionated Anki export) or similar, so that interested users can do this.
