### ISSUE TITLE
Vocabulary grid

### ISSUE THREAD

**Issue by GrimPixel** [jzohrab/lute-v3#247]
**Is your feature request related to a problem? Please describe.**

There could be an overview of vocabulary.

**Describe the solution you'd like**

Vocabulary can be arranged in a grid, with the translation in tooltips.

**Additional context**

An unfinished example is available at https://codeberg.org/GrimPixel/Quiz_Grid

![grid](https://github.com/jzohrab/lute-v3/assets/39795763/4f64caef-0060-457e-8024-003f6731b084)

**Comment by jzohrab** [comment]
I can't understand what this is at all, or how it would be applicable to all languages.  Is this for korean only?

If I had a set of terms in German (Buch, Bett, Madchen, Tashe), how would this be used?

**Comment by GrimPixel** [comment]
Yes, they are arranged in a grid, too, with a different set of length and width. The shorter words are arranged in a column and the longer ones in another.

**Comment by jzohrab** [comment]
I can’t see the need for this, it’s certainly not anything I’ve ever seen in any language tool. I’ll close this as I don’t feel it’s in scope for lute itself, it feels like a very personal preference.  Unfortunately time is extremely limited.
