### ISSUE TITLE
Feature request: Add option to remove image from word

### ISSUE THREAD

**Issue by PsychoThinker** [jzohrab/lute-v3#25]
It happened to me, that I chose an image for a word, and then I realized, that it would be very difficult to find an image that represented that particular word.

It would be great to be able to click on a selected image again and have that image separate from the word.

**Comment by jzohrab** [comment]
In branch `issue_25_remove_images`.  Deletion not done yet but selection is.

**Comment by jzohrab** [comment]
Fixed in `develop`: click the image in the term form to highlight it (red border), and then hit delete or backspace to delete it.

**Comment by jzohrab** [comment]
Released in 3.1.4.
