### ISSUE TITLE
Feature request: option to hide columns from home page

### ISSUE THREAD

**Issue by jamesdeluk** [jzohrab/lute-v3#250]
Currently there is Title, Language, Tags, Word count, Statuses, and Actions.

All of mine are the same language and I don't use tags.

It would be useful to be able to hide these columns to save space on the screen and declutter (especially if https://github.com/jzohrab/lute-v3/issues/24 is implemented)

**Comment by M-Biggles** [comment]
I like the idea of having a little Settings cog just above the header row which will have the option to show/hide various columns. Placement? Either to the left of 'Show X entries' or to the right of the search box.

**Comment by jzohrab** [comment]
The data tables library has some kind of show hide feature, have to find out what extensions are needed.

**Comment by jzohrab** [comment]
Looking at this, might be quick.  This will help with adding more data to the table (unique word count, author, date added, etc).

**Comment by jzohrab** [comment]
Blocked due to a problem with the datatables.min.js file, which prevents using a "colvis" (column visibility) button.

Forum thread: https://datatables.net/forums/discussion/78180/migrating-from-1-13-10-to-2-0-0-errors-datatable-is-not-defined#latest

**Comment by jzohrab** [comment]
Now have a new dt issue with the "colvis" button, https://datatables.net/forums/discussion/78238/possible-2-0-0-error-with-colvis-and-datatables-min-js/p1?new=1, so this stays on hold.

Pushed `issue_250_book_col_visibility` with the code, broken due to colvis.

**Comment by jzohrab** [comment]
Blocked until datatables can be updated

**Comment by jzohrab** [comment]
Datatables updated, this is now feasible, but I can't sort out what should be done for the UI.

**Comment by jzohrab** [comment]
Done in `develop`, added a small gear in the table footer, moved some things around to try to have less clutter.

**Comment by jzohrab** [comment]
Launched in 3.2.4.

**Comment by jamesdeluk** [comment]
Is there a way to make this permanent, i.e. not have to change the settings every time Lute is started?

**Comment by jzohrab** [comment]
@jamesdeluk - I have no idea ... it may be save-able, that would be a new issue.  Something like this might be a start: https://datatables.net/forums/discussion/73851/colvis-and-statesave
