### ISSUE TITLE
Show component words of multi-word terms

### ISSUE THREAD

**Issue by jzohrab** [jzohrab/lute-v3#251]
Sometimes long terms "hide" other terms.  It would be nice to see those shorter terms as well, somehow.

e.g. from Discord discussion:

![Image](https://github.com/jzohrab/lute-v3/assets/1637133/199c82f1-c5a9-47ec-925c-a320ead149c8)

"Homaj Rajtoj" is also declared as a Term, but the longer term hides it.  When you hover over  'Universala Deklaracio de Homaj Rajtoj', you want 'Homaj Rajtoj'  to show up.

**Comment by jzohrab** [comment]
I'm running into this a lot in Vietnamese:

> <img width="225" alt="image" src="https://github.com/jzohrab/lute-v3/assets/1637133/12a5ff36-d991-4d07-859f-c906d15c7b27">

these three components all have their own meanings and sometimes show up separately, but all together they mean "a story".  Since it's so foreign, seeing the components would be helpful.

**Comment by M-Biggles** [comment]
> I'm running into this a lot in Vietnamese:

Yup, I figured you would.

**Comment by jzohrab** [comment]
Launched in 3.2.7.
