### ISSUE TITLE
Have a separate “Import book” in “BOOKS”

### ISSUE THREAD

**Issue by GrimPixel** [jzohrab/lute-v3#253]
**Is your feature request related to a problem? Please describe.**

In “Create new Book”, it is confusing that it allows both text and text file on the same page. What if I input text and then select a file to import?

**Describe the solution you'd like**

Move the “Text file” to a new option “Import book” in “BOOKS”, just like “Import web page”.

**Describe alternatives you've considered**

It can be done in another way: have “Import text file” and “Import web page” options are located near the “Text” field; once imported, the text appear in “Text”.

**Comment by jzohrab** [comment]
If you import text _and_ an import file, Lute prevents you from continuing.

I'm going to close this one just for lack of bandwidth: the current situation suffices, even if it's not _great_.  I understand your concern, but a new path requires a different form and endpoint, and it has a low ROI compared to other features in the backlog.

**Comment by GrimPixel** [comment]
Good. I have other priorities, too. I need a rest before coming up with another idea. See you then.
