### ISSUE TITLE
Feature request: translate full page keyboard shortcut

### ISSUE THREAD

**Issue by jamesdeluk** [jzohrab/lute-v3#256]
t = translate word

Shift t = translate paragraph

Maybe one for translate the whole page?

Ctrl shift t reopens the previous tab for me.

Alt shift t could work, although also brings up the menu bar on Firefox.

Shift y perhaps? (as y is next to t)

**Comment by jzohrab** [comment]
Hey there yes this could make sense.  I feel this will be less used than the other items, and too many hot keys is overwhelming. Would a link on the slide out menu do?

**Comment by jamesdeluk** [comment]
A link would also work as you'd only use it once per page.

I also think it would be better if it opened in a separate window i.e. not the same one as the t/shift-t translate.

**Comment by jzohrab** [comment]
Hey @jamesdeluk -- there's a long backlog, so in the interest of getting something usable out asap for you, for a first pass at this I'm just going to add a "control-t" shortcut to translate the full page.  We can revisit later if it's not super-duper, but I think it might just do as a stopgap.

**Comment by jzohrab** [comment]
Added this as v1 implementation in `develop` branch.

**Comment by jzohrab** [comment]
After being told that "control-t" is already assigned in most browsers, I'm switching this back to a link in the slide-out menu.  Progress ... ?

**Comment by jzohrab** [comment]
Launched in 3.2.4.
