### ISSUE TITLE
Sticky book list sorting across sessions

### ISSUE THREAD

**Issue by shetozz** [jzohrab/lute-v3#258]
**Is your feature request related to a problem? Please describe.**

Currently, the sorting in the main table resets to default -title- after each launch of the app -or after the browser times the tab out if in active for a while-

**Describe the solution you'd like**

To save the sorting as a user preference, either as an option in settings or to save the last one the user sorted by.

**Additional context**

Title sorting doesn't work for non-alphabetical languages like Chinese and Japanese. It also doesn't work if you have a ton of books, as you're not necessary reading in alphabetical order, and having to set it each time is a bit inconvenient.

**Comment by jzohrab** [comment]
For a first pass, not having a user preference is easier.  Too many prefs = too many headaches :-)

Thanks for the issue.  :wave:

**Comment by jzohrab** [comment]
Hm, I'm not able to reproduce this one -- tried opening new tabs, starting stopping in dev and prod mode, closing and reopening etc.  The sorting and filtering for the book stays the same.  @shetozz what am I missing?

**Comment by shetozz** [comment]
Not sure, I'm still on 3.1.3a (mandarin fork), so there might be a difference, but I can replicate it with just closing the tab and opening a new one.

**Comment by jzohrab** [comment]
Right, I perhaps try updating ... but I can't see a commit in there that would change it.

**Comment by shetozz** [comment]
Updating fixed the issue, I'll close it with this comment.
