### ISSUE TITLE
RTL text boxes when adding/editing book info

### ISSUE THREAD

**Issue by jzohrab** [jzohrab/lute-v3#261]
Transferred from #165 item D:

(Create new book / Edit page) Text fields (Title and Text) are both incorrectly set as LTR. (Users might still use LTR titles, so it would be best to handle both.)

![D](https://github.com/jzohrab/lute-v3/assets/156795688/ebfc0676-a033-4e9d-82ce-f27f48ebd420)

**Comment by jzohrab** [comment]
> Users might still use LTR titles, so it would be best to handle both.

It would be best, but I don't know how to do that without a fair amount of work (new db field, new UI elements, etc) ... is there a way for users to indicated that it's an LTR title somehow, in the text?

**Comment by jzohrab** [comment]
Fixed in develop as a first step.  If we need to handle both LTR and RTL in the titles (somehow!), that will be a separate issue.

> ![Image](https://github.com/jzohrab/lute-v3/assets/1637133/22ba4c64-616d-4d52-972b-2a0a1adaeeb6)

> ![Image](https://github.com/jzohrab/lute-v3/assets/1637133/f255d4f5-ac70-4326-8fbd-22628fedcb6c)

and changing the lang when creating a book changes it to rtl / ltr as needed

> ![Image](https://github.com/jzohrab/lute-v3/assets/1637133/474ec1c0-805c-4e80-b256-ecd0f4db3038)

**Comment by M-Biggles** [comment]
> > Users might still use LTR titles, so it would be best to handle both.
> 
> It would be best, but I don't know how to do that without a fair amount of work (new db field, new UI elements, etc) ... is there a way for users to indicated that it's an LTR title somehow, in the text?

Yeah, I guess there's some way of doing it with BIDI but I'd just leave it RTL for now and we see if there's some easy way. If not, it can remain as-is.

Thanks for this one! Can't wait to see it in action, @jzohrab !

**Comment by jzohrab** [comment]
Launched in 3.2.1.
