### ISSUE TITLE
404 error

### ISSUE THREAD

**Issue by ElnonaCnidaria** [jzohrab/lute-v3#263]
**Description**

I tried to highlight multiple Chinese characters to combine them to make a word in the dictionary, but it didn't allow me to highlight them. The characters that I was trying to combine are 大义灭亲.  It works to highlight just 大义 or 灭亲. The problem seems to be with connecting 义灭 specifically. 

Error Message:

Version: 3.1.4
You were on: http://localhost:5000/read/9
You were trying to access: http://localhost:5000/read/termform/8/?textparts=

**To Reproduce**

Steps to reproduce the behavior, e.g.:

2. Click on '...'
3. Scroll down to '...'

**Screenshots**
![Screenshot (454)](https://github.com/jzohrab/lute-v3/assets/160289035/bc5548b3-28c1-41dd-8339-56f6be8c20fc)
![Screenshot (455)](https://github.com/jzohrab/lute-v3/assets/160289035/bce1a3d6-25ad-4321-aaac-23a71843481a)
![Screenshot (457)](https://github.com/jzohrab/lute-v3/assets/160289035/87bdf9cb-b95b-45af-8473-b2434acd8c03)

**Extra software info, if not already included in the Description:**

- OS (e.g., iOS, windows): windows
- Browser (e.g., chrome, safari): chrome
- How you've installed Lute (Docker, python, source): Docker
- Version: 3.1.4

**Comment by jzohrab** [comment]
Thank you, that's very annoying.  I believe there are other similar bugs out reported already, but leaving this open until I can get to it.

As a workaround, are you able to create a term using the term listing > action > add new link, with these characters?  And if yes, is that word highlighted in the reading pane?

<img width="202" alt="image" src="https://github.com/jzohrab/lute-v3/assets/1637133/b834322a-5cd2-44f2-a54b-3577f9416b82">

**Comment by ElnonaCnidaria** [comment]
I didn't try creating the term directly, but I added those characters to a different "book" and it worked to highlight it in the second book. After I created the term in the second book, it showed up in the first book as a proper word. 
I also had the highlighting/dictionary term creating problem in a few other spots.

**Comment by jzohrab** [comment]
Thanks, will look into it ... at some point.  As long as you're not blocked, that's great.  Thanks for the issue 👋

**Comment by ElnonaCnidaria** [comment]
No problem. Sounds good. 👍

**Comment by jamesdeluk** [comment]
I've had this with Korean multi-word phrases too.

Creating the term directly via Terms works (including highlighting).

I'll keep note of phrases that cause the issue and add them here.

Windows, Firefox, pip, 3.1.4.

**Comment by jzohrab** [comment]
Hi @ElnonaCnidaria and @jamesdeluk — the recent update has a download backup file link. If you download and send me a zip, perhaps attaching it to this issue, and indicate the book and term, I can get to it quicker.  Thanks!

**Comment by jzohrab** [comment]
As @jamesdeluk says, this is possibly related to resolved issue #271 -- I'll launch that pretty soon as this is annoying in some cases.  Thanks!

**Comment by jzohrab** [comment]
@ElnonaCnidaria - this _may_ have been fixed with the recent launch, let me know.

**Comment by ElnonaCnidaria** [comment]
I updated it, and it seems to be working so far.

**Comment by jzohrab** [comment]
OK, I'll close this issue believing it to be fixed, and if something comes up again we'll look into it as a new issue.  Thank you!
