### ISSUE TITLE
Weird bug on selecting multiwords in first line of demo texts

### ISSUE THREAD

**Issue by jzohrab** [jzohrab/lute-v3#271]
>  ![Image](https://github.com/jzohrab/lute-v3/assets/1637133/b02b73e9-9dd6-4e7b-9738-bc3f8b711079)

"muchacho llamado"

> ![Image](https://github.com/jzohrab/lute-v3/assets/1637133/5c60c2c7-7f28-47c5-8193-170cd0c0367d)

The click-drag thing just stops dragging.

**Comment by jamesdeluk** [comment]
Maybe relates to #263? As

**Comment by jzohrab** [comment]
Fixed in `develop`, needs launch.
