### ISSUE TITLE
Idea: Title from text file filename when creating new book

### ISSUE THREAD

**Issue by jamesdeluk** [jzohrab/lute-v3#272]
Simple idea: When creating a new book, you can use a text file. When you Browse and add it, perhaps the book Title can be replaced with the filename (if it's empty). For example, if the file is called "article about dogs.txt", the Title automatically changes to "article about dogs".

JS pseudo-code (works in the console), `document.getElementById('title').value=document.getElementById('textfile').value.split('\\')[2]`

**Comment by jzohrab** [comment]
Thanks, that seems clear enough!

**Comment by jzohrab** [comment]
Todo/scope:
- add js to the form creation, only replace title if blank
- check .txt files, .pdf, .epub, creation from web

**Comment by jzohrab** [comment]
@jamesdeluk - hoping for some help here.  I'm not sure how to do this, using html controls.  I understand the js snippet works, but I'm not sure how to trigger that from the UI.  Any assistance here would be great.

**Comment by jamesdeluk** [comment]
Hmm, my skills don't extend far beyond little JS snippets for bookmarklets! So not sure about the triggering etc. My hacky solution would add a few lines to (I think) `if form.validate_on_submit():` or `def _get_file_content(filefielddata):`, so the title is pulled in automatically when Save is pressed (only if there is no title already there). That way there's no additional UI/trigger.

**Comment by jzohrab** [comment]
:-)  Cheers.  That wouldn't be consistent UI design, the element should be updated on-screen when the file is added, as opposed to magic happening on submit.  I'll wait until someone comes along with a better solution.  👋

**Comment by jamesdeluk** [comment]
Yeah, I realise it's not ideal. It wouldn't be so bad if there was a message on the page along the lines of "If no title is given, the filename will be used".

Alternatively, a simple HTML button ("Copy filename to title") that runs the JavaScript would also work. To scratch my own itch, I may a userscript: https://greasyfork.org/en/scripts/488111-lute-filename-to-title

**Comment by jzohrab** [comment]
Both of those solutions feel a bit hacky.  I may have found a better solution when I did the recent image import PR: create a custom button that calls click on the file button, and hide the file button.

**Comment by Jayanth-Parthsarathy** [comment]
Hey @jzohrab. I would like to work on this. Please assign this to me.

**Comment by jzohrab** [comment]
That's correct @Jayanth-Parthsarathy , thanks!  If the title is blank, and a file is added, the filename could be used for the title.

This may be messy-ish, and it's not very high priority (to me!) at all, so if it gets weird, feel free to report back for the next person who dares to attempt it. :-)

**Comment by jzohrab** [comment]
@Jayanth-Parthsarathy is doing a much better job on this than I was going to. :-P  Still in progress, but the idea is good.

**Comment by jzohrab** [comment]
Fixed in develop, works great.  Will be in next launch.
