### ISSUE TITLE
Idea: Open random book

### ISSUE THREAD

**Issue by jamesdeluk** [jzohrab/lute-v3#277]
As per the title. A button on the home page that opens a random book for studying/reviewing.

**Comment by jzohrab** [comment]
In the interest of backlog/feature management, I'm going to decline this one ... but perhaps someone else will see it and jump in :-)  Sorry @jamesdeluk , cheers and thanks for your other notes.

**Comment by jamesdeluk** [comment]
Fair enough! For now, I've made a simple bookmarklet. It only works for the books currently visible, but it does the job. I guess a "proper" implementation would use the database to get the book IDs.

```js
var bookTitles = document.getElementsByClassName('book-title');
var hrefs = [];
for (var i = 0; i < bookTitles.length; i++) {
  var href = bookTitles[i].getAttribute('href');
  hrefs.push(href);
}
var randomIndex = Math.floor(Math.random() * hrefs.length);
var randomHref = hrefs[randomIndex];
window.location.href = 'http://localhost:5000' + randomHref;
```

And minified and as a bookmarklet:
```js
javascript:(function()%7Bvar%20e%3Ddocument.getElementsByClassName(%22book-title%22)%2Ct%3D%5B%5D%3Bfor(var%20n%3D0%3Bn%3Ce.length%3Bn%2B%2B)t.push(e%5Bn%5D.getAttribute(%22href%22))%3Bvar%20r%3DMath.floor(Math.random()*t.length)%2Co%3Dt%5Br%5D%3Bwindow.location.href%3D%22http%3A%2F%2Flocalhost%3A5001%22%2Bo%3B%7D)()%3B
```

**Comment by jzohrab** [comment]
Well that's pretty slick :-)  Try it out for a while and see how it works for you.

Sometime I find that I want an idea, and then after I use it for a bit, I stop using it, because it doesn't really add much to my fun quotient.  I should really add an API for questions like your book IDs, but haven't thought much about it beyond "I should really add an API."

**Comment by jamesdeluk** [comment]
For context, I add one or two new books/articles every day, each only 100 words or so. Due to this, I will end up having a _lot_ of books. For reviewing purposes, I'll be using my little random bookmarklet, as it will be easier (and more fun!) than clicking through each in order.

**Comment by jzohrab** [comment]
Hey that's fun.  Others might be interested in it, maybe post to the discord?  Cheers!

**Comment by jamesdeluk** [comment]
I don't really use Discord but feel free to post it on my behalf :)

**Comment by M-Biggles** [comment]
> Hey that's fun. Others might be interested in it, maybe post to the discord? Cheers!

I was thinking that Greasemonkey and userscripts could be useful for tweaking little things here and there. Might even help in testing some things. I'll keep a list of them - if more are created, we'll have a little collection.

**Comment by jamesdeluk** [comment]
Any semi-usable ones I'll share on Greasyfork, so they should show here: https://greasyfork.org/en/scripts?q=lute
