### ISSUE TITLE
Unable to select numbers/punctuation at start/end with drag

### ISSUE THREAD

**Issue by jamesdeluk** [jzohrab/lute-v3#279]
If the number is between two words, you can select it:

![image](https://github.com/jzohrab/lute-v3/assets/27723508/7f5b7a2d-9cd6-45f8-ac51-b2bbf760cf23)

However, you can't make a selection starting or ending with a number:

![image](https://github.com/jzohrab/lute-v3/assets/27723508/15e4094e-45b5-4142-b1cd-adfec0b47dfc)

In this situation, I would like to be able to select 12월에 문을 닫으려했지만, as 12월 means December, so is needed for the meaning (my dictionary translates phrases as well as only words).

This also applies to question marks etc. I believe this is because they don't have the class `word`, because, well, they're not words. Adding the class "fixes" this:

![image](https://github.com/jzohrab/lute-v3/assets/27723508/b4aa5633-0e67-4428-bc16-1bbf3db4c8bf)

Is there a workaround, such as a class that enables selection but not saving? Personally I wouldn't even mind if they did count as words/terms and could simply be marked as well known/ignored.

Slight complication: as you can see in the third screenshot, the "word" is actually ` 12`, not simply `12`.

**Comment by jzohrab** [comment]
Hey @jamesdeluk - you might be able to add the digit range 0-9 in your language "word characters".  Can you give that a shot?

**Comment by jamesdeluk** [comment]
Didn't work, either the digit range or the actual number (e.g. 12). I also tried " 12", but that was automatically trimmed. I guess in the processing numbers are removed.

**Comment by jzohrab** [comment]
Checking this briefly.  In my dev db I created an english text `12dog 13 cat mouse42`

With the default english word chars `a-zA-ZÀ-ÖØ-öø-ȳáéíóúÁÉÍÓÚñÑ` it's shown as

> <img width="256" alt="image" src="https://github.com/jzohrab/lute-v3/assets/1637133/4f047940-a652-4f14-9b33-4bd47cd57307">

When I added 0-9 to the word chars (`a-zA-ZÀ-ÖØ-öø-ȳáéíóúÁÉÍÓÚñÑ0-9`) things looked as I expected them:

> <img width="274" alt="image" src="https://github.com/jzohrab/lute-v3/assets/1637133/22cace46-2df2-48ce-aa41-55ee122add3b">

@jamesdeluk can try adding `0-9` to the word chars, and let me know if that works?  Also perhaps you could make a backup of your db and send me the zip so I can check it out.  You might be able to attach a file to this issue.

**Comment by jzohrab** [comment]
(and maybe I've misread the question too)

**Comment by jamesdeluk** [comment]
Oh, my mistake, I added them as terms. Adding as word chars work, although now it's not possible to select the letters without the number - although for me I still think that's better. Thanks!

**Comment by jzohrab** [comment]
ok, I'll close this for now and if something else comes up we can sort it out. :wave:
