### ISSUE TITLE
ChatGPT for dictionary

### ISSUE THREAD

**Issue by Shantibhushan95** [jzohrab/lute-v3#280]
The default dictionaries don't always produce a desired result.

Possible enhancement:
Embedding ChatGPT with suitable configuration, like pre defining the prompt context for our purpose.

The result could be a nicely formed explanation with noun, verb, etc. markers with additional example sentences, usages

**Comment by Shantibhushan95** [comment]
wow, my first search didn't return the already existing similar request! closing.

**Comment by Leonard-44** [comment]
That would be awesome, like smartbook APP or Language Reactor
