### ISSUE TITLE
Update save button functionality on new term page

### ISSUE THREAD

**Issue by imamcr** [jzohrab/lute-v3#301]
Currently, clicking "Save" button on the "New Term" page redirects users to the terms page, disrupting the workflow. Instead, let's reset the form and stay on the same page after saving.

**Comment by jzohrab** [comment]
Successful post for "add new" just needs to go back to the "add new" route, I believe.

The form for the reader should still do what it's doing (flash message and redraw the page).

**Comment by Jayanth-Parthsarathy** [comment]
Hey @jzohrab. I would like to work on this. Please assign this to me.

**Comment by jzohrab** [comment]
It might be tricky … lmk if you get stuck, @Jayanth-Parthsarathy 👋

**Comment by jzohrab** [comment]
Merged into `develop`, thanks to @Jayanth-Parthsarathy 👍
