### ISSUE TITLE
Move vendored js, css into separate folder(s) in lute/static

### ISSUE THREAD

**Issue by jzohrab** [jzohrab/lute-v3#307]
Currently, `lute/static/css` and `lute/static/js` have some vendored code (i.e code pulled from external sources, and committed into the repo).  Vendoring is fine, but these vendored files should be stored separately.

There are a few libraries:

* jquery
* tagify
* charting
* datatables

and some of these have both js and css.  I think they should go into separate folders under vendor, eg:

```
lute/
    static/
          vendor/
                tagify/
                jquery/
... etc
```

and then the lute templates should be changed to point at the right folders.

**Comment by Jayanth-Parthsarathy** [comment]
Hey @jzohrab. I would love to work on this. Can you please assign this to me?

**Comment by jzohrab** [comment]
Thank you @Jayanth-Parthsarathy 👍

**Comment by jzohrab** [comment]
I'll close this when I try it out a bit more, and do the next release.

**Comment by jzohrab** [comment]
Launched in 3.2.5.  Super, thank you, this has bothered me for a while now. :-)
