### ISSUE TITLE
Add ability to open a new Lute tab from reading page and other locations

### ISSUE THREAD

**Issue by mzraly** [jzohrab/lute-v3#312]
**Is your feature request related to a problem? Please describe.**

When I am reading a book I sometimes want to access other Lute tabs for reference or to make edits that I cannot make in the Lute tab.  Clicking on the Lute icon takes me back to the Lute home page.  Right-clicking on the Lute icon on the reading page only gives me an option to open the image in a new tab, not to open the page in a new tab.  This is inconsistent with the behavior seen when right-clicking on the Lute icon on the home page, which DOES allow you to open a new tab.

**Describe the solution you'd like**

Right-clicking on the Lute icon in the reading page should offer me the option to open the Lute home page in a new tab.

**Describe alternatives you've considered**

None

**Additional context**

None

**Comment by M-Biggles** [comment]
I'm not the only one who was thinking about this! :D

**Comment by Jayanth-Parthsarathy** [comment]
I would like to work on this. Please assign this to me @jzohrab @mzraly

**Comment by jzohrab** [comment]
Cheers, thanks @Jayanth-Parthsarathy :-)

**Comment by jzohrab** [comment]
Fixed by @Jayanth-Parthsarathy in #314 - thank you, will be in the next release. 👍

**Comment by jzohrab** [comment]
Launched in 3.2.5.
