### ISSUE TITLE
Links to lute manual need updates to account for reorganization of files in that repository

### ISSUE THREAD

**Issue by mzraly** [jzohrab/lute-v3#318]
**Description**

Various links to the Lute manual are broken

**To Reproduce**

Go to Terms -> Import Terms, click on the "Bulk Term Import" documentation link.

Go to Terms -> Parent Term mapping, click on the "Bulk Mapping Parent Terms" documentation link.

Go to Settings -> Settings, click on the "?" icon in the Japanese section next to "MECAB_PATH environment vvariable", click on the two "the manual" documentation links.

In all cases listed above the link results in a "Page not found" error.

**Screenshots**

None

**Extra software info, if not already included in the Description:**

- OS (e.g., iOS, windows): Linux
- Browser (e.g., chrome, safari): firefox
- How you've installed Lute (Docker, python, source): pip
- Version: 3.2.4

**Comment by mzraly** [comment]
I can fix this.

**Comment by jzohrab** [comment]
Thanks very much, I don't have a good way to check for broken links automatically yet.  Appreciate the PR!

**Comment by jzohrab** [comment]
Launched in 3.2.5.
