### ISSUE TITLE
Add book text search

### ISSUE THREAD

**Issue by jzohrab** [jzohrab/lute-v3#32]
If I know a book has a term, I just want to search for it somewhere, and have the pages where it shows up.

**Comment by mzraly** [comment]
Workaround: don't paginate, let user use browser search?

**Comment by jzohrab** [comment]
Closing this for now ... I created this issue, and I've never needed it.

**Comment by jzohrab** [comment]
I somehow missed @mzraly 's comment :-) -- not paginating basically can't be done within Lute due to how it processes each page.  Good idea, though.

Let's leave this closed unless someone reeeeeeeeally needs it.  I never have.
