### ISSUE TITLE
Hotkey arrow up and down to increase/decrease status number

### ISSUE THREAD

**Issue by jzohrab** [jzohrab/lute-v3#33]
Hotkey left-right moves to terms, so up/down could change status.

Would need to go up related to the current status.  If multiple terms chosen, could just start with the lowest status.  Go from 1-2-3-4-5-WellKnown, skip "ignored".

The function to update is in lute.js, `handle_keydown` -- at least, that is how I was intending to do it.  If there is a better option, LMK.

**Comment by robby1066** [comment]
I have a pull request just about ready to go for this, but I wanted to double check the multiple terms case. 

In the case where I have three terms selected with different status levels. Let's say:

- una: Well-known
- escuela: Level 5
- basura: Level 1

Upon clicking the up arrow, is the desired behavior the following?

- una: Well-known (no change)
- escuela: Level Well-known
- basura: Level 2

If I understand the multiple terms description above, the terms should increment/decrement relative to their original status, with a max of `well-known` and a min of 1. Does that sound correct?

To illustrate a little further, repeated up arrows would eventually end up with everything as `well-known`, and repeated down arrows would eventually end up with everything as status `1`.

If that sounds correct, I'll do one more pass through the code and send a PR.

**Comment by jzohrab** [comment]
Thats better than what I was thinking, I figured they’d all get set to the
same thing (the lowest). :-)

**Comment by jzohrab** [comment]
Actually based on the above, "If multiple terms chosen, could just start with the lowest status" -- having them all be the same would be easiest to do: loop through all of them, get the lowest, then ajax that value incremented or decremented.  But if you've already done the other more complicated way, that's good too!
