### ISSUE TITLE
Add Audio controls to play text mp3.

### ISSUE THREAD

**Issue by jzohrab** [jzohrab/lute-v3#35]
Store audio in same parent folder as where images are stored, perhaps ... or stream from URI?

Requirements:
- page content to be ajaxed in, not URL-per-page.
- store or stream audio file
- audio player and controls

**Comment by fanyingfx** [comment]
I have a little confusing abut the stream from URI, does that mean the audio may not in the local?
At first I just think to generate the audio file for each  paragraph, so it just need to generate the audio file and play audio file. But considering play the text as full audio, it truly needed a audio player and controls, and maybe have a good reading experience.

Maybe we can integrate the tts service at first? so we can have audio file to play, but there is a problem, I just using the azure tts, it has too many options, awhat UI we can provide to user to make it config eaisy or just in config file as an option?

**Comment by jzohrab** [comment]
> does that mean the audio may not in the local?

I don't know -- perhaps being able to stream audio-only from a site would be useful, but it might be tricky.

I _personally_ don't have much use for streaming from audio URLs or files as a built-in function for Lute, I usually find audio during reading to be distracting, and am happy enough to play audio from iTunes or whatever.  But I can see how some would find it useful.

Integrating a TTS service has its challenges as you've noticed, and each service has its own special settings and characteristics. 
  Adding UI and configuration to simplify usage is a decent idea but as Lute is a free product I'm hesitant to take on work when other solutions would be _good enough_, even if they're not perfect.  I wonder if the _easiest_ option -- at least to get started -- would be to just recommend some of the online TTS services such as NaturalReader or ReadAloud.

**Comment by fanyingfx** [comment]
Ok, I think I need to  make the demo version first in my fork repo, just for the tts and audio play get worked with simplest option, then base on this we can discuss an improved version for the lute.

**Comment by jzohrab** [comment]
Ready to go, docs at https://jzohrab.github.io/lute-manual/usage/audio.html

**Comment by jzohrab** [comment]
Launched in 3 0 6
