### ISSUE TITLE
Chinese Character Dictionary Terms Show Extra Information with Multi-Character Terms

### ISSUE THREAD

**Issue by ElnonaCnidaria** [jzohrab/lute-v3#354]
**Description**

When hovering over a multi-character term, in addition to showing the information for that term, the pop-up dictionary will also show the information for the individual characters which make up the term in the same way that it would show the information for a parent term. 

**To Reproduce**

1. Go to a Chinese character book with a defined multi-character term in which the individual characters which make up the multi-character term are also defined.
2. Hover over the multi-character term.
3. See error

**Screenshots**

![Screenshot (468)](https://github.com/jzohrab/lute-v3/assets/160289035/721af6e4-d250-4f95-aa07-cdd655b6c1cc)

**Extra software info, if not already included in the Description:**

- OS (e.g., iOS, windows): Windows
- Browser (e.g., chrome, safari): Chrome
- How you've installed Lute (Docker, python, source): Docker
- Version: 3.2.7

**Comment by jzohrab** [comment]
Hi there, this is actually intentional :-P - introduced in https://github.com/jzohrab/lute-v3/issues/251

I didn't add a title like "components" vs "parents", I only added a distinguisher when both were present -- trying to avoid screen clutter.  There are other issues to streamline the pop-up, allow interactions, etc.

Before I close this, any other questions or thoughts about it?

**Comment by ElnonaCnidaria** [comment]
Is it possible to make showing the information for the individual characters of multi-character words optional? I'm fine with it showing the information of words that are set as parents, but it gets kind of cluttered and confusing to have that for words that are not marked as parent terms. For example, in the screenshot I attached, the 子 character which by itself has the meaning of "son" is not the same as the two-character word 眸子 which means "pupil of an eye". The two meanings are not related, so it doesn't make sense to have the definition of the 子  character with the word 眸子, and it doesn't make sense to have the unrelated picture either.

**Comment by jzohrab** [comment]
Understood, thanks for the message.  There's an issue for controlling the detail, #236.

About the images -- I'd included those for component terms, and in my cases inclusion makes sense, but not yours as you show.  Hm, tricky.  I still like the idea of showing the component term images, so I created issue https://github.com/jzohrab/lute-v3/issues/355 to at least move them to a place where they're included with the top-level images, as I agree it might get weird.

I'll close this issue as I think it's done with the above answer, but if you add notes I'll see them.  Cheers!
