### ISSUE TITLE
Mobile reading: header and side margin takes up too much space

### ISSUE THREAD

**Issue by jzohrab** [jzohrab/lute-v3#361]
From discord:

> I currently have a few annoyances with the mobile website. It has a big thick forehead/header that house the hamburger menu and page selector. This wastes a lot of vertical real estate that I need while searching dictionaries. And the 2nd biggest annoyance is there is wide borders on the left and right sides which in turn waste a lot of horizontal real estate

makes a lot of sense, should have a more mobile-friendly option.

> ![Image](https://github.com/jzohrab/lute-v3/assets/1637133/ccfaaa19-30ac-4e5c-ad96-4d9bf6508b0e)

**Comment by schlick7** [comment]
![Screenshot_20240321-142137](https://github.com/jzohrab/lute-v3/assets/17865651/3cb90f95-c9d5-4fe3-81ac-c0a9e96218fa)

Here's an example screenshot

**Comment by jzohrab** [comment]
Launched in 3.3.0.
