### ISSUE TITLE
Add "go to next book" on final page of current book

### ISSUE THREAD

**Issue by jzohrab** [jzohrab/lute-v3#373]
With my introductory Vietnamese reading, I have a pile of very short books that I am constantly re-reading and re-listening to:

> ![Image](https://github.com/jzohrab/lute-v3/assets/1637133/85f1171b-d7de-4ff2-b38d-e14c755bd6fd)

These books are _extremely_ short:

> ![Image](https://github.com/jzohrab/lute-v3/assets/1637133/3df2385e-54a1-45ce-9b5c-33ad52f688d5)

I don't want to join them up, they should stay separate, b/c they're separate things with separate audio.  It would be nice on the final page to have a "go to next book" link (which shows the title as a tooltip on hover) so I could quickly get to the next thing in my review list.

Dev notes:

- in the current book table listing, the list of returned book IDs could be saved to the database or in the user session or something, so that on the final page, we could find the next book and render the link.  Perhaps user session is best, it's the lightest weight
- on final page, find the next book id.  If no session info available, no link.  If no next book, no link.  If curr book not found in list, no link.
- the current links are rendered as part of the controller/jinja template, might need to be handled in the controller/app as well, not sure.

**Comment by jzohrab** [comment]
Workaround for me: right-click each title and open in new tab, then read and close. :-P

**Comment by schlick7** [comment]
Could this be a good reason to create "courses" ? Can group sets of book into a folder structure of some sort and then have a next book setting there.
 I was think about this when I saw how cluttered my books page was getting when I was adding a bunch of content. It would be really nice to have all of my podcasts from different sources separated into there own little grouping which would organize and reduce clutter.

**Comment by jzohrab** [comment]
Hey @schlick7 -- The sentence view is literally a sentence-by-sentence view of a book, this is a bit different -- going from book to book, instead of sentence by sentence.  I posted a workaround for this in discord -- for [using bookmarklets to open all book links](https://discord.com/channels/1074759089051160647/1074759090338812015/1222057155113390110) which works nicely for me so I'm going close this issue for now -- the idea of "next book" is really only useful in specific situations like mine, I think!

Grouping books into folders or similar is in #115.

Currently I use tags for organizing podcasts, news articles, etc.  I haven't yet had a need to do further grouping but that may change.

**Comment by schlick7** [comment]
I meant to say that workflow wise what you're doing is close to sentence view.

**Comment by jzohrab** [comment]
Got it, in a way it is.
