### ISSUE TITLE
what port is used by default?  5000 does not work

### ISSUE THREAD

**Issue by onsosb** [jzohrab/lute-v3#380]
Hi,
I installed LWT following your docker instructions and is running under docker-desktop.  Using: http://localhost:5000 does not work.  What is the default port, to run lwt.
Thanks

**Comment by jzohrab** [comment]
Hi there, are you asking about Lute, or LWT?  Lute uses port 5000.

**Comment by jzohrab** [comment]
ref https://jzohrab.github.io/lute-manual/install/install.html#using-docker

**Comment by onsosb** [comment]
I am asking for  LWT listening port.  I did try 5000, I thought it should work with LWT and it did not.

**Comment by jzohrab** [comment]
That’s a different project, I have no idea. This is Lute, not LWT.
