### ISSUE TITLE
Add user pref toggle to not pause audio on click

### ISSUE THREAD

**Issue by jzohrab** [jzohrab/lute-v3#53]
Currently, when the term form is displayed while reading, it sends an event to pause the audio.  Some users want to be able to disable that, i.e. audio continues even when the form is opened.

**Comment by Mycheze** [comment]
Bumping this cause I'd really like audio to continue to play.

**Comment by jzohrab** [comment]
Added in `develop` branch, another recent change facilitated this.  On the settings page:

> ![Image](https://github.com/jzohrab/lute-v3/assets/1637133/f6f71445-2749-4484-b940-1afb5987a57c)

I've tried it out and it seems to work fine, so it will be in the next launch.

**Comment by jzohrab** [comment]
Launched in 3.2.4.
