### ISSUE TITLE
500 internal server error for non-utf-8 file encodings

### ISSUE THREAD

**Issue by quopquai** [jzohrab/lute-v3#67]
**Description**

Whenever I go to create a new book with whatever text file or whatever text file and audio file I get this error message now:

Platform: macOS-13.3-x86_64-i386-64bit

Version: 3.0.6

In docker?: False

Stack trace:

Traceback (most recent call last):
  File "/Users/julisco/my_lute/myenv/lib/python3.8/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/julisco/my_lute/myenv/lib/python3.8/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/julisco/my_lute/myenv/lib/python3.8/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/julisco/my_lute/myenv/lib/python3.8/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/julisco/my_lute/myenv/lib/python3.8/site-packages/lute/book/routes.py", line 81, in new
    b.text = str(content, "utf-8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa6 in position 1680: invalid start byte

**To Reproduce**

just try to create a new Book

- Browser: chrome:
- How you've installed Lute: python

**Comment by jzohrab** [comment]
[1_Matthew_KJV.txt](https://github.com/jzohrab/lute-v3/files/13734499/1_Matthew_KJV.txt)

Sample book that causes failure attached.  Should catch the error and show a better message instead of the failure screen.

**Comment by sakolkar** [comment]
What would be the best scenario for handling the non-UTF8 characters? Is it ok to drop the characters and then flash a message to the user that "cleaning" of the text was performed?

**Comment by sakolkar** [comment]
The `UnicodeDammit` class in the BeautifulSoup4 library might be of some use to us here. If it knows of a Unicode replacement it will perform the replacement for you.

Eg. 
```
>>> from bs4 import UnicodeDammit

>>> with open("1_matt_short.txt", "rb") as f:
...     content = f.read()

>>> content
b'THE GOSPEL ACCORDING TO\rSAINT MATTHEW\r\r\r\r\nCHAPTER 1\r  Hello.\r  18 \xa6 Now.\r\n'

>>> UnicodeDammit(content).unicode_markup
'THE GOSPEL ACCORDING TO\rSAINT MATTHEW\r\r\r\r\nCHAPTER 1\r  Hello.\r  18 ¦ Now.\r\n'
````

**Comment by jzohrab** [comment]
Honestly not sure. I saw the dammit library but it might be safer just to reject the file as a first iteration.  If we did a sub I’d wasn’t to somehow show the user the changes, but maybe that will get tough.

**Comment by jzohrab** [comment]
I've added a message for non-utf-8:

> <img width="1195" alt="image" src="https://github.com/jzohrab/lute-v3/assets/1637133/e877dd21-ee4f-41dd-a43a-8cab36fc39e5">

This is a good first step, along with the new manual faq entry re book utf-8 import errors.

**Comment by jzohrab** [comment]
manual: https://jzohrab.github.io/lute-manual/faq/books/utf-8.html

**Comment by jzohrab** [comment]
Launch in 3.0.9.
