### ISSUE TITLE
Add alternate book import option - i.e. from subtitle files

### ISSUE THREAD

**Issue by jonathonmh** [jzohrab/lute-v3#84]
This relates to discussion on this issue: https://github.com/jzohrab/lute-v3/issues/73, i.e. for importing/ playing youtube.

At a minimum, it would be convenient to create a book from a subtitle file, i.e. srt, vtt, and have lute parse this for only the subtitles (an easy operation).

If issue 73 above is also solved, then the original youtube video URL (with subtitle file) could be the source of the new book creation.

Automatic subtitle translation could be provided for this import, e.g. something like srt_file_translator (a python library).

The above would be valuable for creating _dual-readers_, i.e. in pairs of languages.

**Comment by patrickayoup** [comment]
Having this functionality at a minimum would be more valuable to me than to embed the video in the page and have text-audio sync (although those are definitely nice to haves).

Having a mechanism where I can enter a YouTube URL and generate a book by extracting the title and subtitles would be perfect.

**Comment by jzohrab** [comment]
This may be solved by PR #320 (add srt and vtt support), but it feels like this request is something different, i.e. that this request wants Lute to go out to YouTube or wherever and automagically get the subtitles.  I don't think I'd embed that into Lute, too many things can go wrong, but having another tool available to go get the data and put it in Lute could be nice.

**Comment by patrickayoup** [comment]
Personally for my own use case I mentioned above, I wrote my own scripts to pull the material I need and inject it into lute, not something I need for lute to provide anymore

**Comment by jzohrab** [comment]
PR #320 adds this, so let's say this one is done until a different request is made :-) -- this is in `develop`, will be in the next launch.

**Comment by jzohrab** [comment]
Launched in 3.2.5.
