### ISSUE TITLE
Add "add page before", "add page after", "remove page" reading menu links

### ISSUE THREAD

**Issue by jzohrab** [jzohrab/lute-v3#89]
With epub imports, sometimes it's useful to remove pages.

When creating books, _sometimes_ it's useful to add new pages (at least for MyCheze from Refold, who like to build things as he goes).  When a page is added, Lute should go to the "edit page" screen first, with a blank screen, and then saving should insert the page at the proper location.  It may be better/easier to create the empty `Text` entity in the database beforehand and then redirect, I don't know what would be best.

Todo:

* Add operations to the book class in lute/models/book.py for the above
* Add simple unit tests for each of these ops it tests, ensure that page re-ordering is done correctly
* Add menu options to the sidebar
* Add acceptance test to ensure things are wired up correctly

**Comment by RamSury** [comment]
Yes, the ability to add and delete pages within books would be very welcome. Looking forward to it.

**Comment by jzohrab** [comment]
Added in develop branch.  Right now the menu is pretty ugly, but it works:

![Image](https://github.com/jzohrab/lute-v3/assets/1637133/57586e5f-f312-49a8-9bb9-e360eed2e60f)

**Comment by jzohrab** [comment]
Launched in 3.2.5.
