### ISSUE TITLE
Add language: [Sanskrit]

### ISSUE THREAD

**Issue by RamSury** [jzohrab/lute-v3#90]
* name: Sanskrit
* dict_1: [dictionary-1-uri](https://dsal.uchicago.edu/cgi-bin/app/sanskrit_query.py?qs=###&searchhws=yes&matchtype=default)
* dict_2: [dictionary-2-uri](https://www.bing.com/images/search?q=###&form=HDRSC2&first=1&tsc=ImageHoverTitle)
* sentence_translation: [translation uri](https://translate.google.com/?hl=en&sl=sa&tl=en&text=###&op=translate)
* show_romanization: true
* right_to_left: false
* parser_type: spacedel
* split_sentences: .?!।॥
* split_sentence_exceptions:
* word_chars: a-zA-Z\u0900-\u0963\u0966-\u097F
* character_substitutions: ´='|`='|’='|‘='|...=…|..=‥

```
Title: [बुद्धिमान् शिष्यः]
Source: [url source or similar]

[काशीनगरे एकः पण्डितः अस्ति । पण्डितसमीपम् एकः शिष्यः आगच्छति । शिष्यः वदति - "आचार्य!
विद्याभ्यासार्थम् आगतः ।" पण्डितः शिष्यबुद्धिपरीक्षार्थं पृच्छति - "वत्स, देवः कुत्र अस्ति?" शिष्यः वदति -
'गुरो! देवः कुत्र नास्ति? कृपया भवान् एव समाधानं वदतु ।" सन्तुष्टः गुरुः वदति - "दैवः सर्वत्र अस्ति । देवः
सर्वव्यापी । त्वं बुद्धिमान ।अतः विद्याभ्यासार्थम् अत्रैव वस।"]
```

**Comment by jzohrab** [comment]
Added to the `develop` branch, thanks.  I added another dictionary that seemed ok: https://www.learnsanskrit.cc/translate?search=###&dir=se
