### ISSUE TITLE
Support PDF imports

### ISSUE THREAD

**Issue by jzohrab** [jzohrab/lute-v3#93]
Lute suuports txt and epub imports, it would be nice to support pdf as well.

For epub imports, a user had to make a new simple library to get around licensing problems, so if using a PDF library, it should be a good license, no real restrictions.  The library should have some basic tests.

The changes in the Lute code to support PDF imports would likely be very similar to those for epub imports:

```
# . ---------------
./requirements.txt:openepub==0.0.6
./pyproject.toml:  "openepub>=0.0.6,<1"
# lute ---------------
lute/book/service.py:def get_epub_content(epub_file_field_data):
lute/book/service.py:    Get the content of the epub as a single string.   .... etc

lute/book/forms.py:                ["txt", "epub"],
lute/book/forms.py:                "Please upload a valid .txt or .epub file.",

lute/book/routes.py:    if ext == ".epub":
lute/book/routes.py:        return service.get_epub_content(filefielddata)

lute/templates/book/create_new.html:      <td>{{ form.textfile.label }} <i>(.txt, .epub)</i></td>

# tests ---------------
tests/acceptance/book.feature:    Scenario: I can import an epub file.
tests/acceptance/book.feature:        Given a Spanish book "Hola" from file Hola.epub
```

**Comment by dgc08** [comment]
PyPDF2 seems like a good library: https://github.com/py-pdf/pypdf

**Comment by jzohrab** [comment]
Is the license ok?

**Comment by dgc08** [comment]
As I understand it, we just have to include their copyright notice and then we're fine.

**Comment by jzohrab** [comment]
Merged into `develop` :tada:
