### ISSUE TITLE
Change data management: always store all terms in db, even when unknown (status 0)

### ISSUE THREAD

**Issue by jzohrab** [jzohrab/lute-v3#99]
Currently Lute doesn't actually store unknown words, they're only stored when terms are created.

Per Shetoz in Discord:

```
Hey @jz , can we add the ability to save state0 terms, so the pop-up/tool-tip shows even if the term is technically new?
Use cases for this might be:
1. currently testing a Mandarin parser with @fanyingfx, the parser adds the pronunciation automatically, but I still have to click save on each term for it to show -it's just inconvenient-
2. The more realistic one for others is, exporting pronunciation and definitions from dictionaries for the most common 1 k words or something like that, and having them on demand when you wanna read without interruption.
```

currently, Lute only stores "known words", i.e., words with status >= 1.  In Lute, "unknown words", i.e. those that show up as the light blue new terms while reading, have "status 0", and are not stored in the db.  In many ways, this makes sense: you don't know it, so it shouldn't be in the db, because it kind of doesn't exist for you yet.

Sometimes this creates problems though, or difficulties during usage:

1) when reading, if you click on an "unknown word" from the reading screen, Lute has to parse it when displaying the term form in the top right corner.  Sometimes this creates parsing inconsistencies, which are bugs, such as in issue #193.
2) fancy parsers can't auto-add some information for terms.
3) educators etc can't provide pre-populated lists of vocab, without having them create new "status = 1 (new)" terms.

The code change in the branch addresses the above this way: when a page is opened for reading, it's parsed as usual, but then Lute saves all the new "status = 0" terms it needs for that particular page.  The javascript handlers that pop up the term editing form now can use the new term's ID when opening the form, so it doesn't have to reparse the term.  This fixes point 1 above, and point 2.

Since this branch also lets people import new vocab with "import new terms as unknowns", that means that people can share pre-populated vocab lists without also overwhelming users of that data with a slew of new terms.  It's a nice benefit.

---

## Branch: `issue_99_store_new_terms_on_read`

Remaining todo items:

- [x] saving all new terms required for page render
- [x] the "WoCreated" field should change to today when the user changes the status of the term from 0 to non-0 (currently in this branch, it will be set to when the new placeholder unknown term is added. Related to #305 )
- [x] lute.js should use the word id when looking up the term in the db, not re-parsing it or doing anything strange.
- [x] perhaps multi-word-term creation on reading can change to use the word ids -- that's big change though, potentially.
- [x] csv imports should update status=0 terms even if "update" not checked, should set status to 1 if 0 and status not set
- [x] wait for issue 332 (get rid of bulk parent import)
- [x] fix remaining test failures, if any
- [x] make data cleanup job -- **DONE, endpoint** `http://localhost:5000/term/delete_all_status_0_terms`
- [x] update `lute/__init__.py`, alpha release number, create alpha release on pip
- [x] install alpha release into my prod environment
- [x] announcement for alpha release
- [x] bake for a few days
- [x] merge branch into develop
- [x] beta release and announcement?
- [x] bake
- [x] #359
- [x] actual launch, code unfreeze

**Comment by jzohrab** [comment]
Thoughts:

* if user clicks "delete", what happens?  Record actually deleted, or status just set to 0 again?  If the former, code/data is not simplified.
* if user _really_ wants to delete something, eg an error/nonsense term, what happens?  Status set to some garbage value, like "-1" deleted?  If really deleted, then code/data is not simplified.
* if "nuclear delete" option (completely delete term from db) is present, and a page references that term, would just recreate it on page render, and re-save it.

**Comment by jzohrab** [comment]
Simplifying: will create status-0 terms only when rendering a page, not when first importing.

Big challenge: if a term is created as status-0, it's hidden.  If user tries to create a new term with the same data, then it would cause an integrity error.  Somehow have to delete the old term and create the new one, or map the data, or something.

**Comment by jzohrab** [comment]
Working on this with branch `wip_issue_99_store_new_terms`

It works, but currently there's a lag because of the way it finds terms that need to be created.

```
create-unk-terms summary ------------------
  parsed_tokens: 0.015839
  word_tokens: 0.000088
  unique_word_tokens: 0.000043
  unique_terms find_or_new: 0.357357
  new_terms: 0.000049
  commit: 0.315502
end create-unk-terms summary --------------
```

It's doing this in a sensible-but-naive way, we might be able to manage this with a single db query ... _might_.

**Comment by jzohrab** [comment]
As you navigate through books, there are fewer and fewer terms that need to be created, so the commit time drops a lot.  The find or new part stays pretty much constant.  E.g after flipping back and forth between pages:

```
  parsed_tokens: 0.002748
  word_tokens: 0.000046
  unique_word_tokens: 0.000023
  unique_terms find_or_new: 0.337731
  new_terms: 0.000037
  commit: 0.000006
```

So if the find can be dropped a lot, all will be good.  Currently the code is getting all parsed tokens and checking them one-by-one to see if they exist; that can probably be changed quite a bit, similar to how render/service.py does find_all_Terms_in_string or similar.

**Comment by M-Biggles** [comment]
I've been looking at this one, wondering what the possible purpose could be.

If the user needs the pronunciation, it can be added at term-creation - whether it be manual or automatic. Seems completely redundant and a waste of Jz's time.

**Comment by jzohrab** [comment]
It actually seems like a good change: it can simplify some code and parsing inconsistencies which have turned up occasionally (where a term is parsed one way in context but completely differently when it’s standalone).

Also, a teacher could create stories and give vocabulary lists for the stories, without imposing a status for the words … not necessarily a bad thing.

appreciate the check though :-) time is finite.

**Comment by M-Biggles** [comment]
Well, yeah, if there are some side-effects that are useful and it doesn't create any problems, it's definitely worth doing it. Thanks for explaining further!

**Comment by jzohrab** [comment]
Still to-do:

* the "WoCreated" field should change.  Currently, it will be set to when the new placeholder unknown term is added ... really, it should be set to whatever date/time the user changes the status of the term from 0 to non-0.  Related to #305

**Comment by jzohrab** [comment]
Have some failing tests for the csv import todo item:

```
FAILED tests/features/test_term_import.py::test_status_0_terms_are_updated_if_create_true - AssertionError: created
FAILED tests/features/test_term_import.py::test_status_0_terms_are_set_to_status_1_if_created_but_status_not_set - AssertionError: created
FAILED tests/features/test_term_import.py::test_status_0_terms_not_updated_if_create_false - AssertionError: updated
```

Once these are resolved then I _think_ that's it.  Will need to do a fuller check.

**Comment by jzohrab** [comment]
Fixed those csv import tests, seems consistent.  Now blocked by issue #332 -- waiting for some feedback before pressing ahead with that change, which then un-blocks this one.

**Comment by jzohrab** [comment]
Added data cleanup endpoint `http://localhost:5000/term/delete_all_status_0_terms` in case this needs to be backed out.

**Comment by jzohrab** [comment]
**Alpha release 3.3.0a1 up on pip.**

https://pypi.org/project/lute3/#history

**Comment by jzohrab** [comment]
Skipping some of the todo items, this is good enough to launch.

**Comment by jzohrab** [comment]
Launched in 3.3.0.
